# Generated by Django 6.0.6 on 2026-06-04 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['city']},
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.animal', verbose_name='Zwierzę'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Aplikujący'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Doświadczenie ze zwierzętami'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe zgłoszenie'), ('review', 'W analizie'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone')], default='new', max_length=20, verbose_name='Status wniosku'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Wiek w latach'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('maly', 'Mały'), ('sredni', 'Średni'), ('duzy', 'Duży')], default='sredni', max_length=10, verbose_name='Wielkość'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('available', 'Dostępny'), ('pending', 'W trakcie adopcji'), ('adopted', 'Adoptowany')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Treść wiadomości'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='city',
            field=models.CharField(max_length=100, unique=True, verbose_name='Miasto'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['status'], name='application_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['created_at'], name='application_created_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status'], name='animal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species'], name='animal_species_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['size'], name='animal_size_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['age'], name='animal_age_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read'], name='contact_is_read_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['created_at'], name='contact_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='adoptionapplication',
            constraint=models.UniqueConstraint(fields=('animal', 'applicant'), name='unique_application_per_user_animal'),
        ),
    ]
