# Generated by Django 6.0.6 on 2026-06-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adoptionapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.animal', verbose_name='Zwierzę'),
        ),
    ]
