# Generated by Django 6.0.6 on 2026-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_adoptionapplication_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Miasto'),
        ),
    ]
