# Generated by Django 6.0.5 on 2026-06-04 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shelter_profiles_roles_animal_details_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='ShelterRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=255, verbose_name='Nazwa schroniska')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Miasto')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=9, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('description', models.TextField(blank=True, verbose_name='Opis dzialalnosci')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shelter_requests', to=settings.AUTH_USER_MODEL, verbose_name='Sprawdzone przez')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_requests', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='shelter_req_status_idx'), models.Index(fields=['created_at'], name='shelter_req_created_idx')],
            },
        ),
    ]
