# Generated by Django 6.0.5 on 2026-06-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_adoptionapplication_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite_per_user_animal',
        ),
        migrations.RemoveIndex(
            model_name='shelterregistrationrequest',
            name='shelter_req_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='shelterregistrationrequest',
            name='shelter_req_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='shelterstaff',
            name='shelter_staff_active_idx',
        ),
        migrations.RemoveConstraint(
            model_name='shelterstaff',
            name='unique_user_shelter_role',
        ),
        migrations.RemoveField(
            model_name='shelterregistrationrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='shelterregistrationrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shelterstaff',
            name='shelter',
        ),
        migrations.RemoveField(
            model_name='shelterstaff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='ShelterRegistrationRequest',
        ),
        migrations.DeleteModel(
            name='ShelterStaff',
        ),
    ]
